name: lint, test, build,
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipiline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: install modules
        run: npm install
      - name: build prod project
        run: npm run build:prod
      - name: linting TS
        run: npm run lint:ts
      - name: linting CSS
        run: npm run lint:scss
      - name: unit testing
        run: npm run unit
